# Generated by Django 5.2.5 on 2025-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Card Title')),
                ('suite', models.CharField(choices=[('cups', 'Cups'), ('wands', 'Wands'), ('swords', 'Swords'), ('pentacles', 'Pentacles'), ('major', 'Major Arcana')], max_length=20, verbose_name='Suite')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Card Number')),
                ('image', models.ImageField(upload_to='tarot_cards/', verbose_name='Card Image')),
                ('upright_meaning', models.TextField(verbose_name='Upright Meaning')),
                ('reversed_meaning', models.TextField(verbose_name='Reversed Meaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['suite', 'number', 'title'],
                'unique_together': {('suite', 'number')},
            },
        ),
    ]
