# Generated by Django 5.2.5 on 2025-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='astrological_sign',
            field=models.CharField(blank=True, choices=[('aries', 'Aries'), ('taurus', 'Taurus'), ('gemini', 'Gemini'), ('cancer', 'Cancer'), ('leo', 'Leo'), ('virgo', 'Virgo'), ('libra', 'Libra'), ('scorpio', 'Scorpio'), ('sagittarius', 'Sagittarius'), ('capricorn', 'Capricorn'), ('aquarius', 'Aquarius'), ('pisces', 'Pisces')], max_length=20, null=True, verbose_name='Astrological Sign'),
        ),
        migrations.AddField(
            model_name='tarotcard',
            name='element',
            field=models.CharField(blank=True, choices=[('fire', 'Fire'), ('water', 'Water'), ('air', 'Air'), ('earth', 'Earth')], max_length=20, null=True, verbose_name='Element'),
        ),
    ]
