# Generated by Django 5.2.5 on 2025-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tarotcard_astrological_sign_tarotcard_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='planet',
            field=models.CharField(blank=True, choices=[('sun', 'Sun'), ('moon', 'Moon'), ('mercury', 'Mercury'), ('venus', 'Venus'), ('mars', 'Mars'), ('jupiter', 'Jupiter'), ('saturn', 'Saturn'), ('uranus', 'Uranus'), ('neptune', 'Neptune'), ('pluto', 'Pluto')], max_length=20, null=True, verbose_name='Planet'),
        ),
    ]
