# Generated by Django 4.2.15 on 2025-08-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_user_bio_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
